### ISSUE TITLE
disable plugins 

### ISSUE THREAD

**Issue by RiCoTeRoX** [samme/phaser-parcel#2]
where you put the flag to disable phaser plugins? , like fbook for example.

**Comment by samme** [comment]
Can't be done directly, except in webpack.

You can copy and modify [src/phaser.js](https://github.com/photonstorm/phaser/blob/v3.16.2/src/phaser.js) and then alias that to 'phaser'.

Or, if they fit your game's needs, alias [src/phaser-arcade-physics.js](https://github.com/photonstorm/phaser/blob/v3.16.2/src/phaser-arcade-physics.js) or [src/phaser-core.js](https://github.com/photonstorm/phaser/blob/v3.16.2/src/phaser-core.js) to 'phaser'. They omit the plugins.

**Comment by samme** [comment]
I'd like this too, but it has to be changed in Phaser.
