### ISSUE TITLE
[Query]How to run the release version

### ISSUE THREAD

**Issue by sathyarajshetigar** [samme/phaser-parcel#3]
Hi,
  I made a release build. Now how do I run it?  Just open the index.html? 
That does not work for me.

**Comment by samme** [comment]
npm run start

from your project directory.

**Comment by sathyarajshetigar** [comment]
Path generated is not relative i guess.
which is right?

"build": "parcel build src/index.html --public-url './'",
or
"build": "parcel build src/index.html --public-url ./",

**Comment by samme** [comment]
After `npm run build`, _dist/index.html_ should contain something like

    <script defer src="app.533fb44d.js"></script>

What is yours?

**Comment by sathyarajshetigar** [comment]
this is what it generates
src="%27./%27/app.5782082a.js"

**Comment by sathyarajshetigar** [comment]
I guess this is how it should be
--public-url . without quotes

**Comment by samme** [comment]
I'll change it then.
