### ISSUE TITLE
codesandbox example is down

### ISSUE THREAD

**Issue by vuldin** [samme/phaser-parcel#4]
https://codesandbox.io/s/github/samme/phaser-parcel

Apologies for not being able to fix this yet, but I just noticed the codesandbox example (link in description of github repo) is not working with the following error: `Unexpected frame by generating stack`

![image](https://user-images.githubusercontent.com/310946/58435126-08545780-808d-11e9-8832-5b1a729b551d.png)

**Comment by samme** [comment]
> Unable to open 'colors.js': File not found
> (file:///sandbox/node_modules/colors.css/js/colors.js).

This is strange. No problem when running it locally.

**Comment by vuldin** [comment]
In that case https://codesandbox.io/s/qjz5t

I just removed the `colors` import and replaced `colors.red` with 'red'.

**Comment by samme** [comment]
This works, without the colors dependency: <https://codesandbox.io/s/phaserparcel-z3ore>
