### ISSUE TITLE
JSON assests load

### ISSUE THREAD

**Issue by AleksandrSl** [samme/phaser-parcel#5]
Not an issue really, but I found that json assets have some "troubles" loading with Parcel.
For example, if I require json file as follows:
```
static ParticlesAtlas = new Asset("particles", {
    texture: require("./res/img/particles.png"),
    atlas: require("./res/img/particles.json")
})
```
it's loaded as file not url and gives following error
```
Uncaught TypeError: this.url.indexOf is not a function
    at JSONFile.File (File.js:97)
    at new JSONFile (JSONFile.js:70)
    at new AtlasJSONFile (AtlasJSONFile.js:73)
    at LoaderPlugin.atlas (AtlasJSONFile.js:235)
    at loadAtlas (assets.js:87)
```

Maybe you know how to deal with this properly?
The only way I found - change `json` extension to something like `._json`

**Comment by samme** [comment]
> Uncaught TypeError: this.url.indexOf is not a function

This is https://github.com/photonstorm/phaser/issues/5125.

You could switch to Phaser v3.22 or use [parcel-plugin-static-files-copy](https://github.com/elwin013/parcel-plugin-static-files-copy) instead of requiring assets.

**Comment by AleksandrSl** [comment]
Thank you so much!
