### ISSUE TITLE
Bundling sprite atlases

### ISSUE THREAD

**Issue by jfred1979** [samme/phaser-parcel#6]
Any luck bundling sprite atlases using imports/file globs? 

Using `import images from './assets/*.*';` I can get the correct URL for all of my assets, but with sprite atlases the path to the image files are going to be baked into the JSON. I'm trying to solve this without using the file copy plugin, as it seems that Parcel 2's dev server does not play well with static assets that weren't bundled this way.

Have you encountered this at all?

**Comment by samme** [comment]
Is it `load.multiatlas()`?

**Comment by jfred1979** [comment]
Yes, that's what I'm currently using for sprite atlas loading.

**Comment by samme** [comment]
Proper thing would be to make a Parcel plugin, but I don't know enough about that.

You can modify the atlas JSON: https://github.com/samme/phaser-parcel/blob/multiatlas/src/BootScene.js

**Comment by jfred1979** [comment]
I was thinking that might be the thing to do, thanks for the feedback!
