### ISSUE TITLE
Error loading JSON

### ISSUE THREAD

**Issue by VadeanFlaviuAlexandru** [samme/phaser-parcel#9]
So I'm new with phaser and I'm currently trying to follow a dungeon crawler tutorial. I'm using this template https://github.com/samme/phaser-parcel and when i load a JSON 

```
//BootScene
    this.load.image("tiles", images.grass)
    this.load.tilemapTiledJSON('forest', 'assets/forest.json')
```
```
//PlayScene
    const map = this.make.tilemap({ key: 'forest' })
    const tileset = map.addTilesetImage('forest', 'tiles')
```
i get errors like
```
Invalid JSON: forest
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
I put the grass.png, forest.tmj and forest.json in src/assets but i think the problem is that the .json doesn't appear in the dist folder. Any help? If a solution is to try [parcel-plugin-static-files-copy](https://github.com/elwin013/parcel-plugin-static-files-copy) , sadly, i dont know how to start using it so im gonna need some help there.

**Comment by VadeanFlaviuAlexandru** [comment]
Sadly, some type has passed and i started using another template, the webpack one. I decided to do so, since another guy also had problems with this template? Weird. Thanks for answering samme! Appreciated anywho :)

**Comment by samme** [comment]
https://github.com/samme/phaser-parcel/blob/tilemap/src/BootScene.js

**Comment by samme** [comment]
https://github.com/samme/phaser-parcel/tree/static-files-copy
